### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'image_ids'

### ISSUE THREAD

**Issue by nikhilcms** [holms-ur/fine-tuning#8]
Error occurred while run template.py of maskrcnn tuned page. I Modified all changes. but not able to solve this issue.

**Comment by joheras** [comment]
Could you send me the error that was generated?

**Comment by Bourne-M** [comment]
> Could you send me the error that was generated?
Process Process-41:

Traceback (most recent call last):
  File "/home/mogaoding/anaconda3/envs/tabledect/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/mogaoding/anaconda3/envs/tabledect/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mogaoding/anaconda3/envs/tabledect/lib/python3.6/site-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "/home/zhouyufei/Work/Code/fine-tuning-master/Mask_RCNN-master/mrcnn/model.py", line 1675, in data_generator
    image_ids = np.copy(dataset.image_ids)
AttributeError: 'NoneType' object has no attribute 'image_ids'

**Comment by joheras** [comment]
It seems that it is not reading the images. Would it be possible to send me the dataset (or part of it) and code to try to reproduce the problem? My email address is joheras at gmail.com

**Comment by Srini-1981** [comment]
Hi Joheras,
Firstly, wanted to thank you for the wonderful repository and appreciate your efforts for open sourcing the code. We are trying to fine tune the tables with our own dataset. Data verification looks good with annotations and image files. Getting the same error as mentioned by above users. Also tried with various tensorflow and keras versions but no luck, still it is failing with same error during the training. 
I have added a log statement before it fetches the training file, what I am suspecting is it is somehow utilizing the first file in the epoch and making short of one file for the steps, hence the error. For example: I am just doing the training with 5 files to narrow down the problem, epoch somehow using the first file and only 4 files remains for the 5 steps so might be the error? Below are the logs with masking some of the paths, any help will be greatly appreciated.

Epoch 1/2

 training file in progress C:\..\pdf-page-01.xml
1/5 [=====>........................] - ETA: 1:57 - loss: 4.1185 - rpn_class_loss: 0.0352 - rpn_bbox_loss: 0.4488 - mrcnn_class_loss: 1.2684 - mrcnn_bbox_loss: 0.6037 - mrcnn_mask_loss: 1.7625
 training file in progress C:\..\pdf-page-04.xml
2/5 [===========>..................] - ETA: 1:20 - loss: 4.5562 - rpn_class_loss: 0.3978 - rpn_bbox_loss: 0.8985 - mrcnn_class_loss: 1.1269 - mrcnn_bbox_loss: 0.6775 - mrcnn_mask_loss: 1.4555
 training file in progress C:\..\pdf-page-10.xml
3/5 [=================>............] - ETA: 51s - loss: 4.1844 - rpn_class_loss: 0.2664 - rpn_bbox_loss: 0.7914 - mrcnn_class_loss: 0.9270 - mrcnn_bbox_loss: 0.6436 - mrcnn_mask_loss: 1.5559 
 training file in progress C:\..\pdf-page-1.xml
4/5 [=======================>......] - ETA: 25s - loss: 3.8967 - rpn_class_loss: 0.2041 - rpn_bbox_loss: 0.7172 - mrcnn_class_loss: 0.7498 - mrcnn_bbox_loss: 0.6495 - mrcnn_mask_loss: 1.5761
 training file in progress C:\..\pdf-page-2.xml
Traceback (most recent call last):

  File "<ipython-input-6-57bcb5146813>", line 1, in <module>
    model.train(train_set, None, learning_rate=config.LEARNING_RATE, epochs=2, layers='heads')

  File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\mask_rcnn-2.1-py3.7.egg\mrcnn\model.py", line 2374, in train
    use_multiprocessing=True,

  File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\keras\engine\training.py", line 2244, in fit_generator
    max_queue_size=max_queue_size)

  File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\keras\engine\training.py", line 2362, in evaluate_generator
    generator_output = next(output_generator)

  File "C:\Users\mommasani.srinivasul\AppData\Local\Continuum\anaconda3\envs\mask-rcnn\lib\site-packages\mask_rcnn-2.1-py3.7.egg\mrcnn\model.py", line 1675, in data_generator
    image_ids = np.copy(dataset.image_ids)

AttributeError: 'NoneType' object has no attribute 'image_ids'

**Comment by Srini-1981** [comment]
Just a note, one another user also raised the same issue - https://github.com/matterport/Mask_RCNN/issues/2051

**Comment by joheras** [comment]
Could you send me the dataset with those 5 images and annotations? I have tried to reproduce the error with my datasets and it seems to work. You can share it with me via my email: joheras@gmail.com

**Comment by Srini-1981** [comment]
Hello Joheras,
This issue got resolved after specifying the test or validation dataset to the model during training instead of None. Need another information, will open a other issue.

Thanks and Regards,
Srini.
